name: Learn build and push image to Docker

on:
  push:
    branchs: [ "test" ]

env:
  REGISTRY: docker.io
  DOCKER_HUB_NAMESPACE: nlcthong1997
  IMAGE_NAME: learn-github-cicd

jobs:
  push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Using github runner repo
        uses: actions/checkout@v3
      
      # - name: Use packege extenal Docker - Build and push image
      #   uses: mr-smithers-excellent/docker-build-push@v6
      #   with:
      #     image: ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.IMAGE_NAME }}
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Login Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}
